language: python
services:
  - docker

branches:
  only:
  - master
  - /\d+\.\d+/
  - /\d+\.\d+\.\d+/

env:
  - BOTO_CONFIG=/dev/null

script:
# build
- bash build_scripts/freeze_requirements.sh
- bash build_scripts/build_package.sh
# dry run
- pip install --no-cache-dir dist/kompos*.tar.gz && kompos --verbose -h

# Output something every 5 minutes or Travis kills the job
- while sleep 5m; do echo "=====[ $SECONDS seconds still running ]====="; done &
# build docker image
- docker build -f build_scripts/Dockerfile -t kompos .
# Killing background sleep loop
- kill %1

before_deploy:
  - git add requirements.txt
deploy:
  - provider: pypi
    skip_cleanup: true
    user: adobe
    password:
      secure: "LqEa3g4oF1SELYOlTFg/eoLb/NloM/0b9y+VceOd9aFLC7JZ8hg7OF6i1XwMGPl6jQB0eWkGsTBLoKxsPzJf39oDyWlK01wkSTTvNF50aXzAVGTaTx/PuD7YBYavk7da1GsfPI8+moXq56ggQkuOFTNSYbiDBNmQNcxMhgCxOPWZYbwJDNKGyenSeqFMp/hC9j2BizZs7LG9xFr8lLugLLr38iXC4azQKOiTk8HiW8C9L9Bs0wqj6PnKEDuz6xU1FxJIXsrttCUtoOrFTiR4gXpXuBLimXjGIifGUcERa2o64mhXvTJYbTeOA8h7iUnoCQDUfWhvzQMwlFx8DA/Z+/quzKBnU6Skv707RrMGiyDKDi1TME1OnzweNvWdSUSQtooVH0Dd38o/NfefFdBapvon26czSltNbZLnKFM2q3uR2/TdiCf71E6L2VFt0nwOFE7DhNGWUbQR0bN6z/yiYmw9Qxjqa9LJ1mHfTdVbB2Sr8uaTW1j4lbSUu8tCF8ueGpfBnM+sOEKo974IAT2knJ1GPNnHIjb/uTFS/VRR8ZzZRfVdD6imLPoSxkpLIMpa6T8AI93HfEhRSKECOxzw2wB/q/NSBpLvkDvWnXJLxGol7g9oELcGn3TWLuhjnyhBVvHD8QhZ+KOSYTB4fOvaLDeaaUajqvInOHgjQKkr4CM="
    on:
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key: "$GITHUB_API_KEY"
    file_glob: true
    file: "dist/**/*"
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: bash build_scripts/docker_push.sh
    on:
      tags: true
