language: python
services:
  - docker

branches:
  only:
  - master
  - /\d+\.\d+/
  - /\d+\.\d+\.\d+/

env:
  - BOTO_CONFIG=/dev/null

script:
# build
- bash build_scripts/freeze_requirements.sh
- bash build_scripts/build_package.sh
# dry run
- pip install --no-cache-dir dist/kompos*.tar.gz && kompos --verbose -h

# Output something every 5 minutes or Travis kills the job
- while sleep 5m; do echo "=====[ $SECONDS seconds still running ]====="; done &
# build docker image
- docker build -f build_scripts/Dockerfile -t kompos .
# Killing background sleep loop
- kill %1

before_deploy:
  - git add requirements.txt
deploy:
  - provider: pypi
    skip_cleanup: true
    user: adobe
    password:
      secure: "dVNoyK/1X3jojtTVyr3EDkuwKl/K4qY8uVwmqM0uRyPAt93jsJZu623zvmxsbns9T23SmoWUgQyxIasVt1eNVnHRfN09MfBcIxSVJdzpQzpPoRq/o1LPYRFliFO4h081Tg+o3H/UakOHmrg8TGEO8U6yj2FWcW6GJLLvAF6m3M6iEtxbZ0J1yVdsDanBqrXF4CtYVtMdcL5vjUu3Ac2T/Oib9bIH+Y+0WSlxHOTsa3JMKRkJ39l2ZZdM2n2APfyR53/qc8lxO+/nnje058TlPhhi9SKK9H+GHx1RcHv38Pxfa9JRGrYY16J56xsaV5gRj6B2ppC7BNzOo7adOB2i5C/UQjN2S5EiBnIfUiuUIjrhX4YDICItRy3ozqB5wyN+EwW1EA5KNTv+7mzzrchZ12AzhupFOnqW3q//3cJGABvDuH/bePNXWUD2I24fY5CDVhEDHxdssLgfp/Cw8vGOFTbFOK8iqnrGhHifNpBN7C1pe7K7qMlTm+sYvz9AqbPfO/2/6HFyUMuSv8FE8jP6Ye9dAhpO0SiBmPQF5774RaoooX6bjpDsr5sD1urMvXDOh3AC3K1LtYw1+s/mWX+4GNe55LYESKUYsy7xIUUhTLoTaZ0suB8dkOWhfperQdva4/2/W8IxOeKjc/jfenIVk/fQY7jq1XG93g0EzHexX4U="
    on:
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key: "$GITHUB_API_KEY"
    file_glob: true
    file: "dist/**/*"
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: bash build_scripts/docker_push.sh
    on:
      tags: true
