---
komposconfig:
  compositions:
    source:
      local_path: "./compositions/terraform"
      root_path: ""
    order:
      terraform:
        - cluster
    properties:
      cluster:
        output_subdir: "clusters"
    system_keys:
      terraform: [provider, terraform]
      tfe:       [workspaces, composition, tfe]

  terraform:
    version: "v1.12.2"
    versioned_module_sources: true
    versioned_extension: ".tf.versioned"

  tfe:
    generation_config:
      generate_compositions: true
      base_output_dir:        "./generated"
      use_composition_output_dir: true
      versioned_extension:    ".tf.versioned"
    workspaces_config:
      generate:            true
      config_key:          "workspaces"
      workspaces_sub_dir:  "workspaces"
      workspace_extension: ".workspace.yaml"
    tfvars_config:
      extension: ".tfvars.yaml"
      filename:  "generated"
